"""Add reward

Revision ID: 0144c1da0fe6
Revises: d1396c067972
Create Date: 2021-02-01 17:33:41.112025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0144c1da0fe6'
down_revision = 'd1396c067972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('giver_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('coin_amount', sa.Integer(), nullable=False),
    sa.Column('note_to_receiver', sa.String(), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['giver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_giver_id'), 'reward', ['giver_id'], unique=False)
    op.create_index(op.f('ix_reward_id'), 'reward', ['id'], unique=False)
    op.create_index(op.f('ix_reward_receiver_id'), 'reward', ['receiver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_receiver_id'), table_name='reward')
    op.drop_index(op.f('ix_reward_id'), table_name='reward')
    op.drop_index(op.f('ix_reward_giver_id'), table_name='reward')
    op.drop_table('reward')
    # ### end Alembic commands ###
