"""Add is_category

Revision ID: 017a2ab5d597
Revises: 43be589a3aca
Create Date: 2021-04-17 23:46:34.275362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017a2ab5d597'
down_revision = '43be589a3aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('is_category', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'is_category')
    # ### end Alembic commands ###
