"""Add editor for comment

Revision ID: 021af3771390
Revises: 9cc77f9fff00
Create Date: 2021-03-22 11:52:13.152673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021af3771390'
down_revision = '9cc77f9fff00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('editor', sa.String(), server_default='wysiwyg', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'editor')
    # ### end Alembic commands ###
