"""Update user model

Revision ID: 0281d8fd326a
Revises: b838801fce91
Create Date: 2020-12-30 22:36:07.441756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0281d8fd326a'
down_revision = 'b838801fce91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('addable_member', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'addable_member')
    # ### end Alembic commands ###
