"""Add submission archive desc text

Revision ID: 031d89b0d6ea
Revises: 9a8a72e3fa0c
Create Date: 2021-06-10 00:04:34.131388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031d89b0d6ea'
down_revision = '9a8a72e3fa0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissionarchive', sa.Column('description_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissionarchive', 'description_text')
    # ### end Alembic commands ###
