"""Update

Revision ID: 055c3cdb6b04
Revises: a8802e4a70f4
Create Date: 2021-12-04 01:39:12.058936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '055c3cdb6b04'
down_revision = 'a8802e4a70f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissionsuggestion', 'accepted_diff_base',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissionsuggestion', 'accepted_diff_base',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
