"""Add description editor field

Revision ID: 05c3a952ea62
Revises: 021af3771390
Create Date: 2021-03-23 18:08:14.520950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c3a952ea62'
down_revision = '021af3771390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('description_editor', sa.String(), server_default='wysiwyg', nullable=False))
    op.add_column('submission', sa.Column('description_editor', sa.String(), server_default='wysiwyg', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'description_editor')
    op.drop_column('question', 'description_editor')
    # ### end Alembic commands ###
