"""Update fields

Revision ID: 06369b058ac1
Revises: 3ad68389b887
Create Date: 2021-05-15 15:26:52.671708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06369b058ac1'
down_revision = '3ad68389b887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'body_prerendered')
    op.drop_column('answer', 'prerendered_at')
    op.alter_column('answer_upvotes', 'answer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('answer_upvotes', 'voter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('article', 'body_prerendered')
    op.drop_column('article', 'prerendered_at')
    op.drop_column('article', 'body_prerendered_text')
    op.drop_column('comment', 'body_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('body_html', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('body_prerendered_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('prerendered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('body_prerendered', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('answer_upvotes', 'voter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('answer_upvotes', 'answer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('answer', sa.Column('prerendered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('body_prerendered', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
