"""Add submission_contributors

Revision ID: 096f816e6921
Revises: 7b009fd9bbda
Create Date: 2021-06-11 00:13:54.449906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096f816e6921'
down_revision = '7b009fd9bbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_contributors',
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_contributors')
    # ### end Alembic commands ###
