"""Add feed

Revision ID: 13285c952687
Revises: 69f40011f79e
Create Date: 2021-01-30 13:24:51.245550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13285c952687'
down_revision = '69f40011f79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_activity_id'), 'feed', ['activity_id'], unique=False)
    op.create_index(op.f('ix_feed_id'), 'feed', ['id'], unique=False)
    op.create_index(op.f('ix_feed_receiver_id'), 'feed', ['receiver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_receiver_id'), table_name='feed')
    op.drop_index(op.f('ix_feed_id'), table_name='feed')
    op.drop_index(op.f('ix_feed_activity_id'), table_name='feed')
    op.drop_table('feed')
    # ### end Alembic commands ###
