"""Fix json model

Revision ID: 13401d048f7d
Revises: b501e111ef53
Create Date: 2021-03-07 19:15:20.524346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13401d048f7d'
down_revision = 'b501e111ef53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'introduction')
    op.add_column('user', sa.Column('education_experiences', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('work_experiences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'work_experiences')
    op.drop_column('user', 'education_experiences')
    op.add_column('profile', sa.Column('introduction', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
