"""Add ViewCountSubmission

Revision ID: 14897e2b7927
Revises: 4794c0c3c743
Create Date: 2025-07-23 14:35:18.968583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14897e2b7927'
down_revision = '4794c0c3c743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewcountsubmission',
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('submission_id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index(op.f('ix_viewcountsubmission_submission_id'), 'viewcountsubmission', ['submission_id'], unique=False)
    op.alter_column('viewcountanswer', 'answer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'viewcountanswer', ['answer_id'])
    op.create_unique_constraint(None, 'viewcountarticle', ['article_id'])
    op.alter_column('viewcountquestion', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'viewcountquestion', ['question_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'viewcountquestion', type_='unique')
    op.alter_column('viewcountquestion', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'viewcountarticle', type_='unique')
    op.drop_constraint(None, 'viewcountanswer', type_='unique')
    op.alter_column('viewcountanswer', 'answer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_viewcountsubmission_submission_id'), table_name='viewcountsubmission')
    op.drop_table('viewcountsubmission')
    # ### end Alembic commands ###
