"""Add some top flags

Revision ID: 14e2a7adb2c6
Revises: 77bf3df9f84d
Create Date: 2021-01-11 19:26:26.565203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e2a7adb2c6'
down_revision = '77bf3df9f84d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('is_placed_at_question_top', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('question', sa.Column('is_placed_at_home', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('question', sa.Column('is_placed_at_site_top', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'is_placed_at_site_top')
    op.drop_column('question', 'is_placed_at_home')
    op.drop_column('answer', 'is_placed_at_question_top')
    # ### end Alembic commands ###
