"""Add profession_topics_json

Revision ID: 1da7e93fd803
Revises: c8fd907cf166
Create Date: 2021-11-25 10:44:22.800753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da7e93fd803'
down_revision = 'c8fd907cf166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profession_topics_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profession_topics_json')
    # ### end Alembic commands ###
