"""Add unsubscription

Revision ID: 1df1637c47e7
Revises: 473e1d2a75a4
Create Date: 2021-01-30 23:29:41.735494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df1637c47e7'
down_revision = '473e1d2a75a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('enable_deliver_unread_notifications', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user', sa.Column('unsubscribe_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unsubscribe_token')
    op.drop_column('user', 'enable_deliver_unread_notifications')
    # ### end Alembic commands ###
