"""Add submission archive description editor field

Revision ID: 1e95c68901bb
Revises: 5a29cea6c435
Create Date: 2021-06-04 20:37:13.027754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e95c68901bb'
down_revision = '5a29cea6c435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissionarchive', sa.Column('description_editor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissionarchive', 'description_editor')
    # ### end Alembic commands ###
