"""Update user model

Revision ID: 2149dde81b01
Revises: 0281d8fd326a
Create Date: 2020-12-31 13:30:57.201424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2149dde81b01'
down_revision = '0281d8fd326a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('flags', sa.String(), nullable=True))
    op.add_column('user', sa.Column('sent_invitataions', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sent_invitataions')
    op.drop_column('user', 'flags')
    # ### end Alembic commands ###
