"""Update answer upvote model

Revision ID: 3081fd03a6fb
Revises: ebc3062bc724
Create Date: 2021-01-11 01:21:54.051169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3081fd03a6fb'
down_revision = 'ebc3062bc724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_answer_upvotes_answer_id'), 'answer_upvotes', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_upvotes_voter_id'), 'answer_upvotes', ['voter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_upvotes_voter_id'), table_name='answer_upvotes')
    op.drop_index(op.f('ix_answer_upvotes_answer_id'), table_name='answer_upvotes')
    # ### end Alembic commands ###
