"""Add rpeorts

Revision ID: 3325c7bab9af
Revises: 61871dbc7ba7
Create Date: 2022-01-09 10:44:22.233400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3325c7bab9af'
down_revision = '61871dbc7ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Enum('SPAM', 'OFF_TOPIC', 'RUDE_OR_ABUSIVE', 'NEEDS_IMPROVEMENT', 'RIGHT_INFRINGEMENT', 'DUPLICATE', 'NEED_MODERATOR_INTERVENTION', name='reportreason'), nullable=False),
    sa.Column('reason_comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_answer_id'), 'report', ['answer_id'], unique=False)
    op.create_index(op.f('ix_report_article_id'), 'report', ['article_id'], unique=False)
    op.create_index(op.f('ix_report_author_id'), 'report', ['author_id'], unique=False)
    op.create_index(op.f('ix_report_comment_id'), 'report', ['comment_id'], unique=False)
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    op.create_index(op.f('ix_report_question_id'), 'report', ['question_id'], unique=False)
    op.create_index(op.f('ix_report_reason'), 'report', ['reason'], unique=False)
    op.create_index(op.f('ix_report_submission_id'), 'report', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_submission_id'), table_name='report')
    op.drop_index(op.f('ix_report_reason'), table_name='report')
    op.drop_index(op.f('ix_report_question_id'), table_name='report')
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_index(op.f('ix_report_comment_id'), table_name='report')
    op.drop_index(op.f('ix_report_author_id'), table_name='report')
    op.drop_index(op.f('ix_report_article_id'), table_name='report')
    op.drop_index(op.f('ix_report_answer_id'), table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###
