"""Payment model

Revision ID: 37da2a0a005c
Revises: 3b7fbbbf91d1
Create Date: 2020-12-26 23:19:12.042214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37da2a0a005c'
down_revision = '3b7fbbbf91d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coinpayment', 'payee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coinpayment', 'payer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coinpayment', 'payer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coinpayment', 'payee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
