"""Add view count tables

Revision ID: 39bea5109b9e
Revises: 6162e247214e
Create Date: 2025-07-20 19:01:31.565999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39bea5109b9e'
down_revision = '6162e247214e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewcountarticle',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'view_count'),
    sa.UniqueConstraint('article_id', 'view_count')
    )
    op.create_index(op.f('ix_viewcountarticle_article_id'), 'viewcountarticle', ['article_id'], unique=False)
    op.create_table('viewcountquestion',
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'view_count'),
    sa.UniqueConstraint('question_id', 'view_count')
    )
    op.create_index(op.f('ix_viewcountquestion_question_id'), 'viewcountquestion', ['question_id'], unique=False)
    op.create_table('viewcountanswer',
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.PrimaryKeyConstraint('answer_id', 'view_count'),
    sa.UniqueConstraint('answer_id', 'view_count')
    )
    op.create_index(op.f('ix_viewcountanswer_answer_id'), 'viewcountanswer', ['answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_viewcountanswer_answer_id'), table_name='viewcountanswer')
    op.drop_table('viewcountanswer')
    op.drop_index(op.f('ix_viewcountquestion_question_id'), table_name='viewcountquestion')
    op.drop_table('viewcountquestion')
    op.drop_index(op.f('ix_viewcountarticle_article_id'), table_name='viewcountarticle')
    op.drop_table('viewcountarticle')
    # ### end Alembic commands ###
