"""Add draft_editor

Revision ID: 3ad68389b887
Revises: 0683eb57352d
Create Date: 2021-04-24 16:03:53.212122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad68389b887'
down_revision = '0683eb57352d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('draft_editor', sa.String(), server_default='wysiwyg', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'draft_editor')
    # ### end Alembic commands ###
