"""Payment model

Revision ID: 3b7fbbbf91d1
Revises: 6c3071d8d022
Create Date: 2020-12-26 23:15:59.146322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7fbbbf91d1'
down_revision = '6c3071d8d022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
