"""Update flag

Revision ID: 3b8106237cf3
Revises: 14e2a7adb2c6
Create Date: 2021-01-11 20:36:56.451555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8106237cf3'
down_revision = '14e2a7adb2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_question_is_placed_at_home'), 'question', ['is_placed_at_home'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_is_placed_at_home'), table_name='question')
    # ### end Alembic commands ###
