"""Remove deprecated fields

Revision ID: 3e61d9fd232c
Revises: d9e2d499d67a
Create Date: 2021-03-15 18:26:07.796528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e61d9fd232c'
down_revision = 'd9e2d499d67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'invitation_token')
    op.drop_column('user', 'invitation_token_issued_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invitation_token_issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('invitation_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
