"""Update articles model

Revision ID: 3f9f62883bbc
Revises: 5d2c2140d1ad
Create Date: 2021-01-26 23:01:02.154146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9f62883bbc'
down_revision = '5d2c2140d1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('article', sa.Column('title_draft', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'title_draft')
    op.drop_column('article', 'is_published')
    # ### end Alembic commands ###
