"""Remove view counters

Revision ID: 4300e970447a
Revises: 9e6cfa47d06b
Create Date: 2021-01-24 19:19:09.903397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4300e970447a'
down_revision = '9e6cfa47d06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'view_times')
    op.drop_column('question', 'view_times')
    op.drop_column('user', 'profile_view_times')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_view_times', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('question', sa.Column('view_times', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('answer', sa.Column('view_times', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
