"""Update answer model

Revision ID: 44b4ccd5cdfc
Revises: ccddb38c98c2
Create Date: 2021-01-15 18:57:26.144069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b4ccd5cdfc'
down_revision = 'ccddb38c98c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('editor', sa.String(), server_default='wysiwyg', nullable=False))
    op.add_column('answer', sa.Column('is_autosaved', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('answer', sa.Column('math_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('answer', 'source_format',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'source_format',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('answer', 'math_enabled')
    op.drop_column('answer', 'is_autosaved')
    op.drop_column('answer', 'editor')
    # ### end Alembic commands ###
