"""Not nullable UUIDs

Revision ID: 473e1d2a75a4
Revises: 36266ab34428
Create Date: 2021-01-30 17:12:38.351220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473e1d2a75a4'
down_revision = '36266ab34428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=False)
    op.alter_column('article', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=False)
    op.alter_column('articlecolumn', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=False)
    op.alter_column('comment', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=False)
    op.alter_column('question', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=False)
    op.alter_column('site', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=False)
    op.alter_column('topic', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=False)
    op.alter_column('user', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=True)
    op.alter_column('topic', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=True)
    op.alter_column('site', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=True)
    op.alter_column('question', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=True)
    op.alter_column('comment', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=True)
    op.alter_column('articlecolumn', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=True)
    op.alter_column('article', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=True)
    op.alter_column('answer', 'uuid',
               existing_type=sa.CHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
