"""Add keywords_extracted_at field

Revision ID: 49c39ab108d8
Revises: bc9b289d6c53
Create Date: 2021-03-24 17:17:38.496139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c39ab108d8'
down_revision = 'bc9b289d6c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('keywords_extracted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'keywords_extracted_at')
    # ### end Alembic commands ###
