"""Update question model

Revision ID: 4c0ee489cfa1
Revises: 7895dbceddfa
Create Date: 2021-02-08 12:09:52.200686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c0ee489cfa1'
down_revision = '7895dbceddfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('question', sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=True))
    op.drop_column('question', 'is_hidden_by_moderator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('is_hidden_by_moderator', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('question', 'is_hidden')
    op.alter_column('comment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
