"""Add editor field to archives

Revision ID: 4f3bbe1eeaa6
Revises: c803c015f56b
Create Date: 2021-03-16 15:30:37.501477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3bbe1eeaa6'
down_revision = 'c803c015f56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archive', sa.Column('editor', sa.String(), server_default='wysiwyg', nullable=False))
    op.add_column('articlearchive', sa.Column('editor', sa.String(), server_default='wysiwyg', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articlearchive', 'editor')
    op.drop_column('archive', 'editor')
    # ### end Alembic commands ###
