"""Update nullable

Revision ID: 584772b747a3
Revises: e8574b6cdddb
Create Date: 2022-01-28 22:36:52.089904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584772b747a3'
down_revision = 'e8574b6cdddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articlearchive', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articlearchive', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
