"""Update user model

Revision ID: 5ff8d34a8126
Revises: 09f028729ac8
Create Date: 2021-01-22 10:59:14.030130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff8d34a8126'
down_revision = '09f028729ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('personal_relation', sa.String(), nullable=True))
    op.add_column('user', sa.Column('invitation_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('invitation_token_issued_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'invitation_token_issued_at')
    op.drop_column('user', 'invitation_token')
    op.drop_column('invitation', 'personal_relation')
    # ### end Alembic commands ###
