"""Add featured_at

Revision ID: 61871dbc7ba7
Revises: b9fc0a230cde
Create Date: 2022-01-08 11:30:06.919139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61871dbc7ba7'
down_revision = 'b9fc0a230cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('featured_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('article', sa.Column('featured_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'featured_at')
    op.drop_column('answer', 'featured_at')
    # ### end Alembic commands ###
