"""Add keywords for question

Revision ID: 621513063323
Revises: 49c39ab108d8
Create Date: 2021-03-24 17:52:02.123180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621513063323'
down_revision = '49c39ab108d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('question', sa.Column('keywords_extracted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'keywords_extracted_at')
    op.drop_column('question', 'keywords')
    # ### end Alembic commands ###
