"""Add answer suggest edit model

Revision ID: 63627588f0c9
Revises: 92fae726b416
Create Date: 2021-12-25 09:59:51.633689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63627588f0c9'
down_revision = '92fae726b416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answersuggestedit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=20), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('description_text', sa.String(), nullable=True),
    sa.Column('description_editor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_diff_base', sa.JSON(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answersuggestedit_answer_id'), 'answersuggestedit', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answersuggestedit_author_id'), 'answersuggestedit', ['author_id'], unique=False)
    op.create_index(op.f('ix_answersuggestedit_id'), 'answersuggestedit', ['id'], unique=False)
    op.create_index(op.f('ix_answersuggestedit_uuid'), 'answersuggestedit', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answersuggestedit_uuid'), table_name='answersuggestedit')
    op.drop_index(op.f('ix_answersuggestedit_id'), table_name='answersuggestedit')
    op.drop_index(op.f('ix_answersuggestedit_author_id'), table_name='answersuggestedit')
    op.drop_index(op.f('ix_answersuggestedit_answer_id'), table_name='answersuggestedit')
    op.drop_table('answersuggestedit')
    # ### end Alembic commands ###
