"""Update bookmark

Revision ID: 6b93fa0e2613
Revises: eda6a2fac15c
Create Date: 2020-12-28 03:00:04.643470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b93fa0e2613'
down_revision = 'eda6a2fac15c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('personal_introduction', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'personal_introduction')
    # ### end Alembic commands ###
