"""Payment model

Revision ID: 6c3071d8d022
Revises: c590109a43f8
Create Date: 2020-12-26 23:14:28.633352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3071d8d022'
down_revision = 'c590109a43f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coindeposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('authorizer_id', sa.Integer(), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['authorizer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coindeposit_id'), 'coindeposit', ['id'], unique=False)
    op.create_table('coinpayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['payee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coinpayment_id'), 'coinpayment', ['id'], unique=False)
    op.drop_column('profile', 'received_likes')
    op.drop_column('profile', 'received_upvotes')
    op.add_column('user', sa.Column('remaining_coins', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('user', 'remaining_coins')
    op.add_column('profile', sa.Column('received_upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('profile', sa.Column('received_likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_coinpayment_id'), table_name='coinpayment')
    op.drop_table('coinpayment')
    op.drop_index(op.f('ix_coindeposit_id'), table_name='coindeposit')
    op.drop_table('coindeposit')
    # ### end Alembic commands ###
