"""Add user feed setting field

Revision ID: 6d8ddfacf048
Revises: e3ca93163b20
Create Date: 2021-06-13 20:56:05.285570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8ddfacf048'
down_revision = 'e3ca93163b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('feed_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'feed_settings')
    # ### end Alembic commands ###
