"""Payment model

Revision ID: 7699728838be
Revises: 37da2a0a005c
Create Date: 2020-12-26 23:22:07.874221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7699728838be'
down_revision = '37da2a0a005c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
