"""Add application model

Revision ID: 7895dbceddfa
Revises: 842e9e21589b
Create Date: 2021-02-06 01:14:36.245721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7895dbceddfa'
down_revision = '842e9e21589b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('applied_site_id', sa.Integer(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['applied_site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_applicant_id'), 'application', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_application_applied_site_id'), 'application', ['applied_site_id'], unique=False)
    op.create_index(op.f('ix_application_id'), 'application', ['id'], unique=False)
    op.add_column('comment', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('profile', 'is_banned')
    op.drop_column('profile', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('profile', sa.Column('is_banned', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('comment', 'created_at')
    op.drop_index(op.f('ix_application_id'), table_name='application')
    op.drop_index(op.f('ix_application_applied_site_id'), table_name='application')
    op.drop_index(op.f('ix_application_applicant_id'), table_name='application')
    op.drop_table('application')
    # ### end Alembic commands ###
