"""Order outgoing/incoming rewards in model

Revision ID: 7b009fd9bbda
Revises: d727019ca7f0
Create Date: 2021-06-10 23:38:05.857156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b009fd9bbda'
down_revision = 'd727019ca7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reward_created_at'), 'reward', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_created_at'), table_name='reward')
    # ### end Alembic commands ###
