"""Update channel model

Revision ID: 816363389257
Revises: b30886ac002d
Create Date: 2020-12-31 17:30:16.633071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816363389257'
down_revision = 'b30886ac002d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
