"""Add karma

Revision ID: 820e2f9cfb02
Revises: 1df1637c47e7
Create Date: 2021-01-31 00:15:01.361543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820e2f9cfb02'
down_revision = '1df1637c47e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('karma', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'karma')
    # ### end Alembic commands ###
