"""Update model

Revision ID: 831dfdf03a18
Revises: fd40a9df4c39
Create Date: 2021-01-09 10:33:05.055498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831dfdf03a18'
down_revision = 'fd40a9df4c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coinpayment', sa.Column('event_json', sa.String(), nullable=True))
    op.drop_constraint('coinpayment_ref_id_key', 'coinpayment', type_='unique')
    op.create_unique_constraint(None, 'coinpayment', ['event_json', 'payee_id'])
    op.drop_column('coinpayment', 'ref_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coinpayment', sa.Column('ref_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'coinpayment', type_='unique')
    op.create_unique_constraint('coinpayment_ref_id_key', 'coinpayment', ['ref_id'])
    op.drop_column('coinpayment', 'event_json')
    # ### end Alembic commands ###
