"""Update user model

Revision ID: 8b1e740e7911
Revises: 5ff8d34a8126
Create Date: 2021-01-22 12:50:44.033143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1e740e7911'
down_revision = '5ff8d34a8126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github_username', sa.String(), nullable=True))
    op.add_column('user', sa.Column('homepage_url', sa.String(), nullable=True))
    op.add_column('user', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('user', sa.Column('twitter_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitter_username')
    op.drop_column('user', 'linkedin_url')
    op.drop_column('user', 'homepage_url')
    op.drop_column('user', 'github_username')
    # ### end Alembic commands ###
