"""Fix model

Revision ID: 8d11e4de766f
Revises: b9652e802bb7
Create Date: 2021-01-22 14:30:07.653180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d11e4de766f'
down_revision = 'b9652e802bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionarchive', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionarchive', 'title')
    # ### end Alembic commands ###
