"""Update channel model

Revision ID: 8eb6a05d5d19
Revises: a5cefdf035a6
Create Date: 2020-12-30 13:37:28.531365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb6a05d5d19'
down_revision = 'a5cefdf035a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel', 'is_private',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel', 'is_private',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
