"""Add created_at field for Site

Revision ID: 98555907d799
Revises: 13401d048f7d
Create Date: 2021-03-08 00:22:36.495193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98555907d799'
down_revision = '13401d048f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user', 'work_experiences_json')
    op.drop_column('user', 'education_experiences_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('education_experiences_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('work_experiences_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('site', 'created_at')
    # ### end Alembic commands ###
