"""Add task model

Revision ID: 9a630f4121fc
Revises: cd1d0246bf82
Create Date: 2021-03-01 00:55:02.566862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a630f4121fc'
down_revision = 'cd1d0246bf82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('task_definition', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FINISHED', 'FAILED', name='taskstatus'), nullable=False),
    sa.ForeignKeyConstraint(['initiator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_index(op.f('ix_task_initiator_id'), 'task', ['initiator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_initiator_id'), table_name='task')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
