"""Add submission ardchive topic uuids

Revision ID: 9a8a72e3fa0c
Revises: f9cc4868db52
Create Date: 2021-06-10 00:02:50.614138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8a72e3fa0c'
down_revision = 'f9cc4868db52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissionarchive', sa.Column('topic_uuids', sa.JSON(), nullable=True))
    op.add_column('submissionsuggestion', sa.Column('accepted_diff', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissionsuggestion', 'accepted_diff')
    op.drop_column('submissionarchive', 'topic_uuids')
    # ### end Alembic commands ###
