"""Add category_topic for site

Revision ID: 9cc77f9fff00
Revises: 4f3bbe1eeaa6
Create Date: 2021-03-20 23:35:43.957858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc77f9fff00'
down_revision = '4f3bbe1eeaa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('category_topic_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_site_category_topic_id'), 'site', ['category_topic_id'], unique=False)
    op.create_foreign_key(None, 'site', 'topic', ['category_topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='foreignkey')
    op.drop_index(op.f('ix_site_category_topic_id'), table_name='site')
    op.drop_column('site', 'category_topic_id')
    # ### end Alembic commands ###
