"""Add editor to question

Revision ID: 9e6cfa47d06b
Revises: 8d11e4de766f
Create Date: 2021-01-24 18:03:06.158894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6cfa47d06b'
down_revision = '8d11e4de766f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('editor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_question_editor_id'), 'question', ['editor_id'], unique=False)
    op.create_foreign_key(None, 'question', 'user', ['editor_id'], ['id'])
    op.add_column('questionarchive', sa.Column('editor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_questionarchive_editor_id'), 'questionarchive', ['editor_id'], unique=False)
    op.create_foreign_key(None, 'questionarchive', 'user', ['editor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questionarchive', type_='foreignkey')
    op.drop_index(op.f('ix_questionarchive_editor_id'), table_name='questionarchive')
    op.drop_column('questionarchive', 'editor_id')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_index(op.f('ix_question_editor_id'), table_name='question')
    op.drop_column('question', 'editor_id')
    # ### end Alembic commands ###
