"""Update answer upvote model

Revision ID: 9fee55d72d95
Revises: 6a3707257d81
Create Date: 2021-01-11 00:36:54.766141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fee55d72d95'
down_revision = '6a3707257d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_upvotes', sa.Column('cancelled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_upvotes', 'cancelled')
    # ### end Alembic commands ###
