"""Add articles

Revision ID: a4e5d081e50a
Revises: 4300e970447a
Create Date: 2021-01-26 21:59:08.357923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e5d081e50a'
down_revision = '4300e970447a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articlecolumn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articlecolumn_id'), 'articlecolumn', ['id'], unique=False)
    op.create_index(op.f('ix_articlecolumn_owner_id'), 'articlecolumn', ['owner_id'], unique=False)
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('article_column_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('upvotes_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['article_column_id'], ['articlecolumn.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_article_column_id'), 'article', ['article_column_id'], unique=False)
    op.create_index(op.f('ix_article_author_id'), 'article', ['author_id'], unique=False)
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)
    op.create_table('subscribed_article_columns',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_column_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_column_id'], ['articlecolumn.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('article_topics',
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], )
    )
    op.create_table('articlearchive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articlearchive_article_id'), 'articlearchive', ['article_id'], unique=False)
    op.create_index(op.f('ix_articlearchive_id'), 'articlearchive', ['id'], unique=False)
    op.create_table('articleupvotes',
    sa.Column('cancelled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'voter_id'),
    sa.UniqueConstraint('article_id', 'voter_id')
    )
    op.create_index(op.f('ix_articleupvotes_article_id'), 'articleupvotes', ['article_id'], unique=False)
    op.create_index(op.f('ix_articleupvotes_voter_id'), 'articleupvotes', ['voter_id'], unique=False)
    op.create_table('bookmarked_articles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('comment', sa.Column('article_id', sa.Integer(), nullable=True))
    op.alter_column('comment', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_comment_article_id'), 'comment', ['article_id'], unique=False)
    op.create_foreign_key(None, 'comment', 'article', ['article_id'], ['id'])
    op.drop_column('question', 'content_history_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('content_history_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_article_id'), table_name='comment')
    op.alter_column('comment', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comment', 'article_id')
    op.drop_table('bookmarked_articles')
    op.drop_index(op.f('ix_articleupvotes_voter_id'), table_name='articleupvotes')
    op.drop_index(op.f('ix_articleupvotes_article_id'), table_name='articleupvotes')
    op.drop_table('articleupvotes')
    op.drop_index(op.f('ix_articlearchive_id'), table_name='articlearchive')
    op.drop_index(op.f('ix_articlearchive_article_id'), table_name='articlearchive')
    op.drop_table('articlearchive')
    op.drop_table('article_topics')
    op.drop_table('subscribed_article_columns')
    op.drop_index(op.f('ix_article_id'), table_name='article')
    op.drop_index(op.f('ix_article_author_id'), table_name='article')
    op.drop_index(op.f('ix_article_article_column_id'), table_name='article')
    op.drop_table('article')
    op.drop_index(op.f('ix_articlecolumn_owner_id'), table_name='articlecolumn')
    op.drop_index(op.f('ix_articlecolumn_id'), table_name='articlecolumn')
    op.drop_table('articlecolumn')
    # ### end Alembic commands ###
