"""Add webhook

Revision ID: a55cb56957e2
Revises: fa7a9c06c679
Create Date: 2021-05-16 20:37:27.939624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55cb56957e2'
down_revision = 'fa7a9c06c679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('event_spec', sa.JSON(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('callback_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_id'), 'webhook', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_site_id'), 'webhook', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_site_id'), table_name='webhook')
    op.drop_index(op.f('ix_webhook_id'), table_name='webhook')
    op.drop_table('webhook')
    # ### end Alembic commands ###
