"""Update user model

Revision ID: a5cefdf035a6
Revises: e0bb8baabaa5
Create Date: 2020-12-30 11:31:59.524140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5cefdf035a6'
down_revision = 'e0bb8baabaa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('handle', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_handle'), 'user', ['handle'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_handle'), table_name='user')
    op.drop_column('user', 'handle')
    # ### end Alembic commands ###
