"""Add body_prerendered_text for article

Revision ID: b15af42b3583
Revises: 3870f5780e72
Create Date: 2021-03-24 16:26:54.280392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15af42b3583'
down_revision = '3870f5780e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body_prerendered_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'body_prerendered_text')
    # ### end Alembic commands ###
