"""Update channel model

Revision ID: b30886ac002d
Revises: 2149dde81b01
Create Date: 2020-12-31 17:27:39.835773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30886ac002d'
down_revision = '2149dde81b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'updated_at')
    # ### end Alembic commands ###
