"""Add audit log model

Revision ID: b501e111ef53
Revises: 9a630f4121fc
Create Date: 2021-03-02 01:46:18.644218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b501e111ef53'
down_revision = '9a630f4121fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ipaddr', sa.String(), nullable=False),
    sa.Column('api', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_id'), 'auditlog', ['id'], unique=False)
    op.create_index(op.f('ix_auditlog_ipaddr'), 'auditlog', ['ipaddr'], unique=False)
    op.create_index(op.f('ix_auditlog_user_id'), 'auditlog', ['user_id'], unique=False)
    op.create_index(op.f('ix_auditlog_uuid'), 'auditlog', ['uuid'], unique=True)
    op.create_unique_constraint(None, 'feed', ['activity_id', 'receiver_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feed', type_='unique')
    op.drop_index(op.f('ix_auditlog_uuid'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_user_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_ipaddr'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_id'), table_name='auditlog')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
