"""Update answer model

Revision ID: b838801fce91
Revises: 8eb6a05d5d19
Create Date: 2020-12-30 17:26:10.837316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b838801fce91'
down_revision = '8eb6a05d5d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('site', 'public_writable_answer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('site', 'public_writable_comment',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('site', 'public_writable_question',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'public_writable_question',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('site', 'public_writable_comment',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('site', 'public_writable_answer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('answer', 'is_published')
    # ### end Alembic commands ###
