"""Update user model

Revision ID: b86c5b5477fd
Revises: db11135cb499
Create Date: 2021-02-12 11:11:39.328645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86c5b5477fd'
down_revision = 'db11135cb499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_editor_mode', sa.String(), server_default='wysiwyg', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'default_editor_mode')
    # ### end Alembic commands ###
