"""Add comment body_text field

Revision ID: b8d3e3432d39
Revises: a2c4da7f3afc
Create Date: 2021-03-30 14:13:50.104724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d3e3432d39'
down_revision = 'a2c4da7f3afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('body_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'body_text')
    # ### end Alembic commands ###
