"""Update

Revision ID: b9fc0a230cde
Revises: 63627588f0c9
Create Date: 2021-12-25 11:16:50.510981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fc0a230cde'
down_revision = '63627588f0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_contributors',
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('answersuggestedit', sa.Column('body', sa.String(), nullable=True))
    op.add_column('answersuggestedit', sa.Column('body_text', sa.String(), nullable=True))
    op.add_column('answersuggestedit', sa.Column('body_editor', sa.String(), nullable=True))
    op.drop_column('answersuggestedit', 'description')
    op.drop_column('answersuggestedit', 'description_editor')
    op.drop_column('answersuggestedit', 'description_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answersuggestedit', sa.Column('description_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('answersuggestedit', sa.Column('description_editor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('answersuggestedit', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('answersuggestedit', 'body_editor')
    op.drop_column('answersuggestedit', 'body_text')
    op.drop_column('answersuggestedit', 'body')
    op.drop_table('answer_contributors')
    # ### end Alembic commands ###
