"""Add keywords for answer

Revision ID: bc9b289d6c53
Revises: b15af42b3583
Create Date: 2021-03-24 17:11:51.062276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9b289d6c53'
down_revision = 'b15af42b3583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('keywords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'keywords')
    # ### end Alembic commands ###
