"""Add forms

Revision ID: be76b1afbc63
Revises: f8e5c9d0d48a
Create Date: 2021-02-03 20:59:50.901763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be76b1afbc63'
down_revision = 'f8e5c9d0d48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=20), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_author_id'), 'form', ['author_id'], unique=False)
    op.create_index(op.f('ix_form_id'), 'form', ['id'], unique=False)
    op.create_index(op.f('ix_form_uuid'), 'form', ['uuid'], unique=True)
    op.create_table('formresponse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_author_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['response_author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formresponse_form_id'), 'formresponse', ['form_id'], unique=False)
    op.create_index(op.f('ix_formresponse_id'), 'formresponse', ['id'], unique=False)
    op.create_index(op.f('ix_formresponse_response_author_id'), 'formresponse', ['response_author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formresponse_response_author_id'), table_name='formresponse')
    op.drop_index(op.f('ix_formresponse_id'), table_name='formresponse')
    op.drop_index(op.f('ix_formresponse_form_id'), table_name='formresponse')
    op.drop_table('formresponse')
    op.drop_index(op.f('ix_form_uuid'), table_name='form')
    op.drop_index(op.f('ix_form_id'), table_name='form')
    op.drop_index(op.f('ix_form_author_id'), table_name='form')
    op.drop_table('form')
    # ### end Alembic commands ###
