"""Add subject to channel

Revision ID: bf88da60488f
Revises: 98fd84b5c1ef
Create Date: 2021-12-18 22:47:41.268911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf88da60488f'
down_revision = '98fd84b5c1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('feedback_subject_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_channel_feedback_subject_id'), 'channel', ['feedback_subject_id'], unique=False)
    op.create_foreign_key(None, 'channel', 'feedback', ['feedback_subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel', type_='foreignkey')
    op.drop_index(op.f('ix_channel_feedback_subject_id'), table_name='channel')
    op.drop_column('channel', 'feedback_subject_id')
    # ### end Alembic commands ###
