"""Add claimed_welcome_test_rewards_with_form_response_id

Revision ID: c07f2ab88c8b
Revises: d19bd4e72e97
Create Date: 2021-02-03 22:56:18.827604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07f2ab88c8b'
down_revision = 'd19bd4e72e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('claimed_welcome_test_rewards_with_form_response_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'formresponse', ['claimed_welcome_test_rewards_with_form_response_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'claimed_welcome_test_rewards_with_form_response_id')
    # ### end Alembic commands ###
