"""Add question upvotes

Revision ID: c376381a1d91
Revises: 3b8106237cf3
Create Date: 2021-01-14 15:19:59.908526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c376381a1d91'
down_revision = '3b8106237cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionupvotes',
    sa.Column('cancelled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'voter_id'),
    sa.UniqueConstraint('question_id', 'voter_id')
    )
    op.create_index(op.f('ix_questionupvotes_question_id'), 'questionupvotes', ['question_id'], unique=False)
    op.create_index(op.f('ix_questionupvotes_voter_id'), 'questionupvotes', ['voter_id'], unique=False)
    op.add_column('question', sa.Column('upvotes_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'upvotes_count')
    op.drop_index(op.f('ix_questionupvotes_voter_id'), table_name='questionupvotes')
    op.drop_index(op.f('ix_questionupvotes_question_id'), table_name='questionupvotes')
    op.drop_table('questionupvotes')
    # ### end Alembic commands ###
