"""Regenerated data model

Revision ID: c590109a43f8
Revises: c96147f8c295
Create Date: 2020-12-26 00:33:34.010022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c590109a43f8'
down_revision = 'c96147f8c295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profile', ['owner_id', 'site_id'])
    op.add_column('user', sa.Column('education_experiences_json', sa.String(), nullable=True))
    op.add_column('user', sa.Column('work_experiences_json', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'work_experiences_json')
    op.drop_column('user', 'education_experiences_json')
    op.drop_constraint(None, 'profile', type_='unique')
    # ### end Alembic commands ###
