"""Add article prerendered

Revision ID: c803c015f56b
Revises: f6a5ec609bf7
Create Date: 2021-03-16 11:29:38.280971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c803c015f56b'
down_revision = 'f6a5ec609bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body_prerendered', sa.String(), nullable=True))
    op.add_column('article', sa.Column('prerendered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'prerendered_at')
    op.drop_column('article', 'body_prerendered')
    # ### end Alembic commands ###
