"""Remove user.about_editor

Revision ID: c8fd907cf166
Revises: 91aa83eae955
Create Date: 2021-11-12 18:30:37.359288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fd907cf166'
down_revision = '91aa83eae955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_editor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_editor', sa.VARCHAR(), server_default=sa.text("'wysiwyg'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
