"""Add question upvotes

Revision ID: ccddb38c98c2
Revises: c376381a1d91
Create Date: 2021-01-14 15:32:48.159670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccddb38c98c2'
down_revision = 'c376381a1d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'questionupvotes', ['question_id', 'voter_id'])
    op.add_column('site', sa.Column('upvote_question_coin_deduction', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'upvote_question_coin_deduction')
    op.drop_constraint(None, 'questionupvotes', type_='unique')
    # ### end Alembic commands ###
