"""Update site model

Revision ID: cd1d0246bf82
Revises: f43df48a00e2
Create Date: 2021-02-27 13:27:29.263287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1d0246bf82'
down_revision = 'f43df48a00e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('auto_approval', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('site', sa.Column('email_domain_suffix_for_application', sa.String(), nullable=True))
    op.add_column('site', sa.Column('min_karma_for_application', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'min_karma_for_application')
    op.drop_column('site', 'email_domain_suffix_for_application')
    op.drop_column('site', 'auto_approval')
    # ### end Alembic commands ###
