"""Update

Revision ID: ce37e212bb64
Revises: bf88da60488f
Create Date: 2021-12-19 14:44:36.257531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce37e212bb64'
down_revision = 'bf88da60488f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('site_creation_subject_subdomain', sa.String(), nullable=True))
    op.add_column('channel', sa.Column('site_creation_subject', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_channel_site_creation_subject_subdomain'), 'channel', ['site_creation_subject_subdomain'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_site_creation_subject_subdomain'), table_name='channel')
    op.drop_column('channel', 'site_creation_subject')
    op.drop_column('channel', 'site_creation_subject_subdomain')
    # ### end Alembic commands ###
