"""Remove content_json

Revision ID: d1396c067972
Revises: 1541eb7cdb55
Create Date: 2021-01-31 19:45:39.489585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1396c067972'
down_revision = '1541eb7cdb55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'content_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('content_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
