"""Update forms

Revision ID: d19bd4e72e97
Revises: be76b1afbc63
Create Date: 2021-02-03 21:03:05.804599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19bd4e72e97'
down_revision = 'be76b1afbc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('form_fields', sa.JSON(), nullable=False))
    op.add_column('formresponse', sa.Column('response_fields', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formresponse', 'response_fields')
    op.drop_column('form', 'form_fields')
    # ### end Alembic commands ###
