"""Add submission model

Revision ID: d706a80ce0a8
Revises: b86c5b5477fd
Create Date: 2021-02-13 01:34:41.604987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd706a80ce0a8'
down_revision = 'b86c5b5477fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=20), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('upvotes_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_author_id'), 'submission', ['author_id'], unique=False)
    op.create_index(op.f('ix_submission_id'), 'submission', ['id'], unique=False)
    op.create_index(op.f('ix_submission_site_id'), 'submission', ['site_id'], unique=False)
    op.create_index(op.f('ix_submission_uuid'), 'submission', ['uuid'], unique=True)
    op.create_table('submission_topics',
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], )
    )
    op.create_table('submissionarchive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissionarchive_id'), 'submissionarchive', ['id'], unique=False)
    op.create_index(op.f('ix_submissionarchive_submission_id'), 'submissionarchive', ['submission_id'], unique=False)
    op.create_table('submissionupvotes',
    sa.Column('cancelled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('submission_id', 'voter_id'),
    sa.UniqueConstraint('submission_id', 'voter_id')
    )
    op.create_index(op.f('ix_submissionupvotes_submission_id'), 'submissionupvotes', ['submission_id'], unique=False)
    op.create_index(op.f('ix_submissionupvotes_voter_id'), 'submissionupvotes', ['voter_id'], unique=False)
    op.add_column('comment', sa.Column('submission_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comment_submission_id'), 'comment', ['submission_id'], unique=False)
    op.create_foreign_key(None, 'comment', 'submission', ['submission_id'], ['id'])
    op.add_column('site', sa.Column('create_submission_coin_deduction', sa.Integer(), server_default='2', nullable=False))
    op.add_column('site', sa.Column('public_writable_submission', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('site', sa.Column('upvote_submission_coin_deduction', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'upvote_submission_coin_deduction')
    op.drop_column('site', 'public_writable_submission')
    op.drop_column('site', 'create_submission_coin_deduction')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_submission_id'), table_name='comment')
    op.drop_column('comment', 'submission_id')
    op.drop_index(op.f('ix_submissionupvotes_voter_id'), table_name='submissionupvotes')
    op.drop_index(op.f('ix_submissionupvotes_submission_id'), table_name='submissionupvotes')
    op.drop_table('submissionupvotes')
    op.drop_index(op.f('ix_submissionarchive_submission_id'), table_name='submissionarchive')
    op.drop_index(op.f('ix_submissionarchive_id'), table_name='submissionarchive')
    op.drop_table('submissionarchive')
    op.drop_table('submission_topics')
    op.drop_index(op.f('ix_submission_uuid'), table_name='submission')
    op.drop_index(op.f('ix_submission_site_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_author_id'), table_name='submission')
    op.drop_table('submission')
    # ### end Alembic commands ###
