"""Update

Revision ID: d7239240b702
Revises: 92e8bf7639ca
Create Date: 2021-11-25 13:05:50.512696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7239240b702'
down_revision = '92e8bf7639ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
