"""Add submission suggestion accepted diff base

Revision ID: d727019ca7f0
Revises: 031d89b0d6ea
Create Date: 2021-06-10 00:13:03.037413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd727019ca7f0'
down_revision = '031d89b0d6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissionsuggestion', sa.Column('accepted_diff_base', sa.JSON(), nullable=True))
    op.drop_column('submissionsuggestion', 'accepted_diff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissionsuggestion', sa.Column('accepted_diff', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('submissionsuggestion', 'accepted_diff_base')
    # ### end Alembic commands ###
