"""Update user model

Revision ID: d81294903342
Revises: 816363389257
Create Date: 2021-01-01 00:57:25.237846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81294903342'
down_revision = '816363389257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_system_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_system_user', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
