"""Add content visibility flag for article

Revision ID: d9e2d499d67a
Revises: f3822eef0de4
Create Date: 2021-03-13 00:48:36.293723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e2d499d67a'
down_revision = 'f3822eef0de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('visibility', sa.Enum('ANYONE', 'REGISTERED', name='contentvisibility'), server_default='ANYONE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'visibility')
    # ### end Alembic commands ###
