"""Update phone number

Revision ID: daa73c481ef0
Revises: 3325c7bab9af
Create Date: 2022-01-15 09:41:41.935640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa73c481ef0'
down_revision = '3325c7bab9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('feed', 'activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user', sa.Column('phone_number_country_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phone_number_subscriber_number', sa.String(), nullable=True))
    op.drop_index('ix_user_phone_number', table_name='user')
    op.create_index(op.f('ix_user_phone_number_country_code'), 'user', ['phone_number_country_code'], unique=True)
    op.create_index(op.f('ix_user_phone_number_subscriber_number'), 'user', ['phone_number_subscriber_number'], unique=True)
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_phone_number_subscriber_number'), table_name='user')
    op.drop_index(op.f('ix_user_phone_number_country_code'), table_name='user')
    op.create_index('ix_user_phone_number', 'user', ['phone_number'], unique=False)
    op.drop_column('user', 'phone_number_subscriber_number')
    op.drop_column('user', 'phone_number_country_code')
    op.alter_column('feed', 'activity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('feed', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
