"""Update comment model

Revision ID: db11135cb499
Revises: fe7fda109125
Create Date: 2021-02-12 10:41:28.923663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db11135cb499'
down_revision = 'fe7fda109125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'is_deleted')
    # ### end Alembic commands ###
