"""Add submission suggestion

Revision ID: dffd3046e10c
Revises: ffcc3b882cf6
Create Date: 2021-06-09 21:42:26.894218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffd3046e10c'
down_revision = 'ffcc3b882cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissionsuggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=20), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('description_text', sa.String(), nullable=True),
    sa.Column('description_editor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissionsuggestion_author_id'), 'submissionsuggestion', ['author_id'], unique=False)
    op.create_index(op.f('ix_submissionsuggestion_id'), 'submissionsuggestion', ['id'], unique=False)
    op.create_index(op.f('ix_submissionsuggestion_submission_id'), 'submissionsuggestion', ['submission_id'], unique=False)
    op.create_index(op.f('ix_submissionsuggestion_uuid'), 'submissionsuggestion', ['uuid'], unique=True)
    op.add_column('site', sa.Column('create_suggestion_coin_deduction', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'create_suggestion_coin_deduction')
    op.drop_index(op.f('ix_submissionsuggestion_uuid'), table_name='submissionsuggestion')
    op.drop_index(op.f('ix_submissionsuggestion_submission_id'), table_name='submissionsuggestion')
    op.drop_index(op.f('ix_submissionsuggestion_id'), table_name='submissionsuggestion')
    op.drop_index(op.f('ix_submissionsuggestion_author_id'), table_name='submissionsuggestion')
    op.drop_table('submissionsuggestion')
    # ### end Alembic commands ###
