"""Update user model

Revision ID: e0bb8baabaa5
Revises: 6b93fa0e2613
Create Date: 2020-12-28 23:09:58.418021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0bb8baabaa5'
down_revision = '6b93fa0e2613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locale_preference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locale_preference')
    # ### end Alembic commands ###
