"""Add suggestion comment

Revision ID: e3ca93163b20
Revises: 096f816e6921
Create Date: 2021-06-13 11:02:16.953333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ca93163b20'
down_revision = '096f816e6921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissionsuggestion', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissionsuggestion', 'comment')
    # ### end Alembic commands ###
