"""Update answer upvote model

Revision ID: ebc3062bc724
Revises: 9fee55d72d95
Create Date: 2021-01-11 01:09:31.224977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc3062bc724'
down_revision = '9fee55d72d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answer_upvotes', ['answer_id', 'voter_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer_upvotes', type_='unique')
    # ### end Alembic commands ###
