"""Update user model

Revision ID: ebc55177cad6
Revises: f66a6a2cbb25
Create Date: 2021-01-02 13:09:36.492212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc55177cad6'
down_revision = 'f66a6a2cbb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'handle',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'handle',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
