"""Remove is_placed_at_question_top

Revision ID: ecce4b4966ab
Revises: da17aa8c10be
Create Date: 2021-03-09 11:28:11.698308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecce4b4966ab'
down_revision = 'da17aa8c10be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'is_placed_at_question_top')
    op.drop_column('question', 'is_placed_at_site_top')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('is_placed_at_site_top', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('answer', sa.Column('is_placed_at_question_top', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
