"""Update bookmark

Revision ID: eda6a2fac15c
Revises: 9990700dc85b
Create Date: 2020-12-27 13:04:46.640413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda6a2fac15c'
down_revision = '9990700dc85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
