"""Add per site karma

Revision ID: efd4a8bf854e
Revises: 2668718cdb60
Create Date: 2021-02-13 22:01:03.086875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd4a8bf854e'
down_revision = '2668718cdb60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'commentupvotes', ['comment_id', 'voter_id'])
    op.add_column('profile', sa.Column('karma', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'karma')
    op.drop_constraint(None, 'commentupvotes', type_='unique')
    # ### end Alembic commands ###
