"""Add content visibility flag for answer

Revision ID: f3822eef0de4
Revises: b087a350779c
Create Date: 2021-03-13 00:01:21.781870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3822eef0de4'
down_revision = 'b087a350779c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    contentvisibility = sa.Enum('ANYONE', 'REGISTERED', name='contentvisibility')
    contentvisibility.create(op.get_bind())
    op.add_column('answer', sa.Column('visibility', sa.Enum('ANYONE', 'REGISTERED', name='contentvisibility'), server_default='ANYONE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'visibility')
    # ### end Alembic commands ###
    contentvisibility = sa.Enum('ANYONE', 'REGISTERED', name='contentvisibility')
    contentvisibility.drop(op.get_bind())
