"""Update index

Revision ID: f3925b9ee72e
Revises: 975224f8aced
Create Date: 2021-08-24 00:20:33.207363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3925b9ee72e'
down_revision = '975224f8aced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_followers_followed_id'), 'followers', ['followed_id'], unique=False)
    op.create_index(op.f('ix_followers_follower_id'), 'followers', ['follower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_followers_follower_id'), table_name='followers')
    op.drop_index(op.f('ix_followers_followed_id'), table_name='followers')
    # ### end Alembic commands ###
