"""Add body prerendered text field

Revision ID: f6a5ec609bf7
Revises: 4fab480583ba
Create Date: 2021-03-16 11:08:21.959884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a5ec609bf7'
down_revision = '4fab480583ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('body_prerendered_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'body_prerendered_text')
    # ### end Alembic commands ###
