"""Add archive model

Revision ID: f911fc3c1871
Revises: 44b4ccd5cdfc
Create Date: 2021-01-15 23:05:23.527969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f911fc3c1871'
down_revision = '44b4ccd5cdfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_answer_id'), 'archive', ['answer_id'], unique=False)
    op.create_index(op.f('ix_archive_id'), 'archive', ['id'], unique=False)
    op.add_column('answer', sa.Column('body_draft', sa.String(), nullable=True))
    op.add_column('answer', sa.Column('draft_saved_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('answer', 'content_history_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('content_history_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('answer', 'draft_saved_at')
    op.drop_column('answer', 'body_draft')
    op.drop_index(op.f('ix_archive_id'), table_name='archive')
    op.drop_index(op.f('ix_archive_answer_id'), table_name='archive')
    op.drop_table('archive')
    # ### end Alembic commands ###
