"""Add submission suggestion topic uuids

Revision ID: f9cc4868db52
Revises: dffd3046e10c
Create Date: 2021-06-09 22:05:05.557806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cc4868db52'
down_revision = 'dffd3046e10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissionsuggestion', sa.Column('topic_uuids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissionsuggestion', 'topic_uuids')
    # ### end Alembic commands ###
