"""Add about in user profile

Revision ID: fa7a9c06c679
Revises: 06369b058ac1
Create Date: 2021-05-16 00:00:51.751172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7a9c06c679'
down_revision = '06369b058ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about', sa.String(), nullable=True))
    op.add_column('user', sa.Column('about_editor', sa.String(), server_default='wysiwyg', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_editor')
    op.drop_column('user', 'about')
    # ### end Alembic commands ###
