"""Add audit log field

Revision ID: fcdd9de59683
Revises: 2d600f126b2a
Create Date: 2021-04-17 09:57:09.485034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdd9de59683'
down_revision = '2d600f126b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'event_json',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('answer', 'body_prerendered_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('auditlog', sa.Column('request_info', sa.JSON(), nullable=True))
    op.alter_column('comment', 'body_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'body_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('auditlog', 'request_info')
    op.alter_column('answer', 'body_prerendered_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('activity', 'event_json',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
