"""Add view times

Revision ID: fed07815fb47
Revises: 8211a967ea0a
Create Date: 2020-12-27 00:55:36.161559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed07815fb47'
down_revision = '8211a967ea0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('view_times', sa.Integer(), server_default='0', nullable=False))
    op.add_column('question', sa.Column('view_times', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('profile_view_times', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_view_times')
    op.drop_column('question', 'view_times')
    op.drop_column('answer', 'view_times')
    # ### end Alembic commands ###
