name: Build Nix Env
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake_dev_shell:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Nix develop
        run: nix develop
      - name: Check size
        run: |
          cd /nix/store
          du -h --max-depth=0
