on:
  push:
    branches:
      - main
      - deploy
      #- dev
  pull_request:
    branches:
      - main
      - deploy

jobs:
  flake_dev_shell:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Nix develop
        run: nix develop
          
