name: Static Analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake_dev_shell:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Set Dependency
        run: |
          cd scripts/static_analysis
          nix develop
